# Consistent version resources and an explicit list of JoF-built signing targets.
# Called after all multiplayer targets have been created.
if(NOT WIN32)
    return()
endif()

if(JOF_VERSION_STRING MATCHES "^([0-9]+)\\.([0-9]+)\\.([0-9]+)")
    set(_default_file_version "${CMAKE_MATCH_1}.${CMAKE_MATCH_2}.${CMAKE_MATCH_3}.0")
else()
    set(_default_file_version "0.0.0.0")
endif()
set(JOF_WINDOWS_FILE_VERSION "" CACHE STRING "Four-part numeric Windows file/product version (empty derives it from the release version)")
if(NOT JOF_WINDOWS_FILE_VERSION)
    set(JOF_WINDOWS_FILE_VERSION "${_default_file_version}")
endif()
if(NOT JOF_WINDOWS_FILE_VERSION MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$")
    message(FATAL_ERROR "JOF_WINDOWS_FILE_VERSION must contain four numeric components")
endif()
string(REPLACE "." ";" _version_parts "${JOF_WINDOWS_FILE_VERSION}")
foreach(_part ${_version_parts})
    if(_part GREATER 65535)
        message(FATAL_ERROR "Windows version components must be at most 65535")
    endif()
endforeach()
string(REPLACE "." "," JOF_RESOURCE_VERSION "${JOF_WINDOWS_FILE_VERSION}")
set(_signing_manifest "")
foreach(_target ${MPEngine} ${MPDed} ${MPGame} ${MPCGame} ${MPUI} ${MPVanillaRenderer} ${MPRend2})
    if(TARGET ${_target})
        get_target_property(_type ${_target} TYPE)
        if(_type STREQUAL "EXECUTABLE")
            set(JOF_RESOURCE_FILE_TYPE "VFT_APP")
            set(JOF_RESOURCE_FILENAME "${_target}${CMAKE_EXECUTABLE_SUFFIX}")
        else()
            set(JOF_RESOURCE_FILE_TYPE "VFT_DLL")
            set(JOF_RESOURCE_FILENAME "${_target}${CMAKE_SHARED_LIBRARY_SUFFIX}")
        endif()
        set(_resource "${CMAKE_CURRENT_BINARY_DIR}/versionfile/${_target}-version.rc")
        configure_file("${CMAKE_SOURCE_DIR}/codemp/win32/jof-version.rc.in" "${_resource}" @ONLY)
        target_sources(${_target} PRIVATE "${_resource}")
        target_compile_definitions(${_target} PRIVATE JOF_GENERATED_VERSION_RESOURCE)
        string(APPEND _signing_manifest "$<TARGET_FILE:${_target}>\n")
    endif()
endforeach()
file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/signing-targets-$<CONFIG>.txt" CONTENT "${_signing_manifest}")
