name: beta-windows-build

on:
  push:
    branches:
      - beta
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "docs/**"

jobs:
  windows:
    name: Windows ${{ matrix.arch }} Release (Beta)
    runs-on: windows-2022

    strategy:
      matrix:
        include:
          - arch: x86
            platform: Win32
          - arch: x86_64
            platform: x64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Create build directory
        run: cmake -E make_directory build

      - name: Configure CMake
        working-directory: ${{ github.workspace }}/build
        shell: bash
        run: |
          cmake .. -A ${{ matrix.platform }} \
            -DCMAKE_INSTALL_PREFIX=bin \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_NUMBER=${{ github.run_number }} \
            -DGIT_SHA=${{ github.sha }} \
            -DGIT_BRANCH=${{ github.ref_name }}

      - name: Build
        working-directory: ${{ github.workspace }}/build
        shell: bash
        run: cmake --build . --config Release -j $NUMBER_OF_PROCESSORS

      - name: Install
        working-directory: ${{ github.workspace }}/build
        shell: bash
        run: cmake --install . --config Release

      - name: Upload Beta Artifact
        uses: actions/upload-artifact@v4
        with:
          name: JoF-beta-windows-${{ matrix.arch }}
          path: build/bin
          if-no-files-found: error
